CONNECT HIBERNATE39/HIBERNATE39

CREATE SEQUENCE SEQ_CLIENTE;
CREATE SEQUENCE SEQ_CONTA;
CREATE SEQUENCE SEQ_CARTAO;

CREATE TABLE CLIENTE
(ID               NUMBER(5)
   CONSTRAINT CLIENTE_PK
   PRIMARY KEY,
 NOME             VARCHAR2(50)
);

CREATE TABLE CONTA
(ID               NUMBER(5)
    CONSTRAINT CONTA_PK
    PRIMARY KEY,
 DATA_ABERTURA    DATE);

CREATE TABLE CARTAO
(ID               NUMBER(5)
    CONSTRAINT CARTAO_PK
    PRIMARY KEY,
 DATA_EMISSAO     DATE);

CREATE TABLE CLIENTE_CONTA_CARTAO
(ID_CARTAO        NUMBER(5)
    CONSTRAINT CLIENTE_CONTA_CARTAO_PK
    PRIMARY KEY
    CONSTRAINT CLIENTE_CONTA_CARTAO_CARTAO_FK
    REFERENCES CARTAO(ID),
 ID_CLIENTE       NUMBER(5)
    CONSTRAINT CLIENTE_CONTA_CARTAO_CLIENT_FK
    REFERENCES CLIENTE(ID),
 ID_CONTA         NUMBER(5)
    CONSTRAINT CLIENTE_CONTA_CARTAO_CONTA_FK
    REFERENCES CONTA(ID));





