-- Exercicio 42

CONNECT HIBERNATE42/HIBERNATE42

CREATE SEQUENCE SEQ_PRODUTO;

CREATE TABLE PRODUTO
(ID             NUMBER(5)
   CONSTRAINT PRODUTO_ID_PK
   PRIMARY KEY,
 NOME           VARCHAR2(30) 
   CONSTRAINT PRODUTO_NOME_NN
   NOT NULL,
 DESCRICAO      VARCHAR2(40),
 LANCE_MINIMO  NUMBER(8,2)
   CONSTRAINT PRODUTO_LANCE_MINIMO_NN
   NOT NULL,
 DATA_CADASTRO  DATE
   CONSTRAINT PRODUTO_DATA_CADASTRO_NN
   NOT NULL,
 DATA_VENDA     DATE);

INSERT INTO PRODUTO(ID, NOME, DESCRICAO, LANCE_MINIMO, DATA_CADASTRO)
VALUES(SEQ_PRODUTO.NEXTVAL, 'TV SAMSUNG 20 POL', 'TV SAMSUNG 20 POL TELA PLANA', 2000, SYSDATE);

INSERT INTO PRODUTO(ID, NOME, DESCRICAO, LANCE_MINIMO, DATA_CADASTRO)
VALUES(SEQ_PRODUTO.NEXTVAL, 'TV PHILIPS 20 POL', 'TV PHILIPS 20 POL TELA PLANA', 2100, SYSDATE);

INSERT INTO PRODUTO(ID, NOME, DESCRICAO, LANCE_MINIMO, DATA_CADASTRO)
VALUES(SEQ_PRODUTO.NEXTVAL, 'TV SAMSUNG 21 POL', 'TV SAMSUNG 21 POL TELA PLANA', 2500, SYSDATE);

INSERT INTO PRODUTO(ID, NOME, DESCRICAO, LANCE_MINIMO, DATA_CADASTRO)
VALUES(SEQ_PRODUTO.NEXTVAL, 'TV PHILIPS 21 POL', 'TV PHILIPS 21 POL TELA PLANA', 2600, SYSDATE);

INSERT INTO PRODUTO(ID, NOME, DESCRICAO, LANCE_MINIMO, DATA_CADASTRO)
VALUES(SEQ_PRODUTO.NEXTVAL, 'TV PHILIPS 22 POL', 'TV PHILIPS 22 POL TELA PLANA', 2700, SYSDATE);

INSERT INTO PRODUTO(ID, NOME, DESCRICAO, LANCE_MINIMO, DATA_CADASTRO)
VALUES(SEQ_PRODUTO.NEXTVAL, 'TV PHILIPS 23 POL', 'TV PHILIPS 23 POL TELA PLANA', 2800, SYSDATE);

INSERT INTO PRODUTO(ID, NOME, DESCRICAO, LANCE_MINIMO, DATA_CADASTRO)
VALUES(SEQ_PRODUTO.NEXTVAL, 'TV PHILIPS 24 POL', 'TV PHILIPS 24 POL TELA PLANA', 2900, SYSDATE);

INSERT INTO PRODUTO(ID, NOME, DESCRICAO, LANCE_MINIMO, DATA_CADASTRO)
VALUES(SEQ_PRODUTO.NEXTVAL, 'TV PHILIPS 25 POL', 'TV PHILIPS 25 POL TELA PLANA', 3000, SYSDATE);

INSERT INTO PRODUTO(ID, NOME, DESCRICAO, LANCE_MINIMO, DATA_CADASTRO)
VALUES(SEQ_PRODUTO.NEXTVAL, 'TV PHILIPS 26 POL', 'TV PHILIPS 26 POL TELA PLANA', 3100, SYSDATE);

INSERT INTO PRODUTO(ID, NOME, DESCRICAO, LANCE_MINIMO, DATA_CADASTRO)
VALUES(SEQ_PRODUTO.NEXTVAL, 'TV PHILIPS 27 POL', 'TV PHILIPS 27 POL TELA PLANA', 3200, SYSDATE);

INSERT INTO PRODUTO(ID, NOME, DESCRICAO, LANCE_MINIMO, DATA_CADASTRO)
VALUES(SEQ_PRODUTO.NEXTVAL, 'TV PHILIPS 28 POL', 'TV PHILIPS 28 POL TELA PLANA', 3300, SYSDATE);

INSERT INTO PRODUTO(ID, NOME, DESCRICAO, LANCE_MINIMO, DATA_CADASTRO)
VALUES(SEQ_PRODUTO.NEXTVAL, 'TV PHILIPS 29 POL', 'TV PHILIPS 29 POL TELA PLANA', 3400, SYSDATE);

INSERT INTO PRODUTO(ID, NOME, DESCRICAO, LANCE_MINIMO, DATA_CADASTRO)
VALUES(SEQ_PRODUTO.NEXTVAL, 'TV PHILIPS 30 POL', 'TV PHILIPS 30 POL TELA PLANA', 3500, SYSDATE);

INSERT INTO PRODUTO(ID, NOME, DESCRICAO, LANCE_MINIMO, DATA_CADASTRO)
VALUES(SEQ_PRODUTO.NEXTVAL, 'TV PHILIPS 31 POL', 'TV PHILIPS 31 POL TELA PLANA', 3600, SYSDATE);

INSERT INTO PRODUTO(ID, NOME, DESCRICAO, LANCE_MINIMO, DATA_CADASTRO)
VALUES(SEQ_PRODUTO.NEXTVAL, 'TV PHILIPS 32 POL', 'TV PHILIPS 32 POL TELA PLANA', 3700, SYSDATE);

INSERT INTO PRODUTO(ID, NOME, DESCRICAO, LANCE_MINIMO, DATA_CADASTRO)
VALUES(SEQ_PRODUTO.NEXTVAL, 'TV PHILIPS 33 POL', 'TV PHILIPS 33 POL TELA PLANA', 3800, SYSDATE);

INSERT INTO PRODUTO(ID, NOME, DESCRICAO, LANCE_MINIMO, DATA_CADASTRO)
VALUES(SEQ_PRODUTO.NEXTVAL, 'TV PHILIPS 34 POL', 'TV PHILIPS 34 POL TELA PLANA', 3900, SYSDATE);

INSERT INTO PRODUTO(ID, NOME, DESCRICAO, LANCE_MINIMO, DATA_CADASTRO)
VALUES(SEQ_PRODUTO.NEXTVAL, 'TV PHILIPS 35 POL', 'TV PHILIPS 35 POL TELA PLANA', 4000, SYSDATE);

INSERT INTO PRODUTO(ID, NOME, DESCRICAO, LANCE_MINIMO, DATA_CADASTRO)
VALUES(SEQ_PRODUTO.NEXTVAL, 'TV PHILIPS 36 POL', 'TV PHILIPS 36 POL TELA PLANA', 4100, SYSDATE);

INSERT INTO PRODUTO(ID, NOME, DESCRICAO, LANCE_MINIMO, DATA_CADASTRO)
VALUES(SEQ_PRODUTO.NEXTVAL, 'TV PHILIPS 37 POL', 'TV PHILIPS 37 POL TELA PLANA', 4200, SYSDATE);

INSERT INTO PRODUTO(ID, NOME, DESCRICAO, LANCE_MINIMO, DATA_CADASTRO)
VALUES(SEQ_PRODUTO.NEXTVAL, 'TV PHILIPS 38 POL', 'TV PHILIPS 38 POL TELA PLANA', 4300, SYSDATE);

INSERT INTO PRODUTO(ID, NOME, DESCRICAO, LANCE_MINIMO, DATA_CADASTRO)
VALUES(SEQ_PRODUTO.NEXTVAL, 'TV PHILIPS 39 POL', 'TV PHILIPS 39 POL TELA PLANA', 4400, SYSDATE);

INSERT INTO PRODUTO(ID, NOME, DESCRICAO, LANCE_MINIMO, DATA_CADASTRO)
VALUES(SEQ_PRODUTO.NEXTVAL, 'TV PHILIPS 40 POL', 'TV PHILIPS 40 POL TELA PLANA', 4500, SYSDATE);

COMMIT;
