DROP TABLE CLIENTE_TELEFONE;
DROP TABLE CLIENTE;
DROP SEQUENCE SEQ_CLIENTE;

CREATE SEQUENCE SEQ_CLIENTE;

CREATE TABLE CLIENTE
(ID               NUMBER(5)
   CONSTRAINT USUARIO_ID_PK
   PRIMARY KEY,
 NOME             VARCHAR2(50),
 SALARIO          NUMBER(9,2));

CREATE TABLE CLIENTE_TELEFONE
(ID               NUMBER(5)
    REFERENCES CLIENTE(ID),
 NUM_ORDEM        NUMBER(3),
 TELEFONE         VARCHAR2(10),
CONSTRAINT CLIENTE_TELEFONE_PK
PRIMARY KEY(ID, NUM_ORDEM));


