DROP USER HIBERNATE01 CASCADE;
CREATE USER HIBERNATE01 IDENTIFIED BY HIBERNATE01;
GRANT CONNECT, RESOURCE TO HIBERNATE01;

CONNECT HIBERNATE01/HIBERNATE01

DROP TABLE CLIENTE CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_CLIENTE;

CREATE SEQUENCE SEQ_CLIENTE;

CREATE TABLE CLIENTE
(NUMERO       NUMBER(5)
   CONSTRAINT CLIENTES_NUMERO_PK
   PRIMARY KEY,
 NOME         VARCHAR2(50),
 SALARIO      NUMBER(9,2));

INSERT INTO CLIENTE
VALUES (SEQ_CLIENTE.NEXTVAL, 'JULIO CESAR', 2500.00);

INSERT INTO CLIENTE
VALUES (SEQ_CLIENTE.NEXTVAL, 'JULIANA SILVA', 1800.00);

INSERT INTO CLIENTE
VALUES (SEQ_CLIENTE.NEXTVAL, 'SERGIO ARANTES', 3800.00);

COMMIT;
