DROP TABLE CATEGORIA CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_CATEGORIA;

CREATE SEQUENCE SEQ_CATEGORIA;

CREATE TABLE CATEGORIA
(ID                NUMBER(5)
   CONSTRAINT CATEGORIA_ID_PK
   PRIMARY KEY,
 NOME              VARCHAR2(30)
   CONSTRAINT CATEGORIA_NOME_NN
   NOT NULL,
 ID_CATEGORIA_PAI  NUMBER(5)
   CONSTRAINT CATEGORIA_CATEGORIA_FK
   REFERENCES CATEGORIA(ID));


INSERT INTO CATEGORIA(ID, NOME, ID_CATEGORIA_PAI)
VALUES(SEQ_CATEGORIA.NEXTVAL, 'COMPUTADOR', NULL);

COMMIT;


